title: KSyP.tech
description: KSyP.tech (Keep Secure, you-will-be Protected) offering resources for each stage of the your IT security risk management process.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  GitHub: https://github.com/kalvinparker/KSyP.tech

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# For copy button on code
enable_copy_code_button: true
