# Header
title: KSyP.tech
description: KSyP.tech (Keep Secure, you-will-be Protected) offering resources for each stage of the your IT security risk management process.

# Template settings
color_scheme: dark # Color scheme supports "light" (default) and "dark"
enable_copy_code_button: true # For copy button on code
theme: just-the-docs

url: https://just-the-docs.github.io

# Banner (no more than 5 links)
aux_links:
  GitHub: https://github.com/kalvinparker/KSyP.tech

# Default pages / products values
defaults:
  - scope:
      path: ""
    values:
      image: /assets/logo.jpg