title: KSyp.tech
description: KSyP (Keep Secure, you-will-be Protected) offering resources for each stage of the your IT security risk management process.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  GitHub: https://github.com/kalvinparker/KSyP.tech
